baseURL = "https://privacypolicy-homura.netlify.com/"
DefaultContentLanguage = "ja"

languageCode = "ja-JP"
title = "Privacy Policies"
theme = "minimal-bootstrap-hugo-theme"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1